#!/bin/bash
NAME="lovehate_app"                                  # Name of the application
DJANGODIR=. # Django project directory
SOCKFILE=./gunicorn.sock  # we will communicte using this unix socket
#USER=dengsl # the user to run as
#GROUP=dengsl # the group to run as
NUM_WORKERS=3                                     # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=lovehate.settings             # which settings file should Django use
DJANGO_WSGI_MODULE=lovehate.wsgi                     # WSGI module name
echo "Starting $NAME as `whoami`"
# Activate the virtual environment
pwd
cd $DJANGODIR
pwd
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH
# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR
# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec gunicorn ${DJANGO_WSGI_MODULE}:application -k gevent \
  --name $NAME \
  --workers $NUM_WORKERS \
  --bind=127.0.0.1:8000 \
  --log-level=debug \
