# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 20:44
from __future__ import unicode_literals

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('love', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(upload_to=common.utils.get_file_path, verbose_name='图片'),
        ),
    ]
