# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='是否内部人员'),
        ),
    ]
